const DATA = {
  "matrix": [
    [
      "AA",
      "AKs",
      "AQs",
      "AJs",
      "ATs",
      "A9s",
      "A8s",
      "A7s",
      "A6s",
      "A5s",
      "A4s",
      "A3s",
      "A2s"
    ],
    [
      "AKo",
      "KK",
      "KQs",
      "KJs",
      "KTs",
      "K9s",
      "K8s",
      "K7s",
      "K6s",
      "K5s",
      "K4s",
      "K3s",
      "K2s"
    ],
    [
      "AQo",
      "KQo",
      "QQ",
      "QJs",
      "QTs",
      "Q9s",
      "Q8s",
      "Q7s",
      "Q6s",
      "Q5s",
      "Q4s",
      "Q3s",
      "Q2s"
    ],
    [
      "AJo",
      "KJo",
      "QJo",
      "JJ",
      "JTs",
      "J9s",
      "J8s",
      "J7s",
      "J6s",
      "J5s",
      "J4s",
      "J3s",
      "J2s"
    ],
    [
      "ATo",
      "KTo",
      "QTo",
      "JTo",
      "TT",
      "T9s",
      "T8s",
      "T7s",
      "T6s",
      "T5s",
      "T4s",
      "T3s",
      "T2s"
    ],
    [
      "A9o",
      "K9o",
      "Q9o",
      "J9o",
      "T9o",
      "99",
      "98s",
      "97s",
      "96s",
      "95s",
      "94s",
      "93s",
      "92s"
    ],
    [
      "A8o",
      "K8o",
      "Q8o",
      "J8o",
      "T8o",
      "98o",
      "88",
      "87s",
      "86s",
      "85s",
      "84s",
      "83s",
      "82s"
    ],
    [
      "A7o",
      "K7o",
      "Q7o",
      "J7o",
      "T7o",
      "97o",
      "87o",
      "77",
      "76s",
      "75s",
      "74s",
      "73s",
      "72s"
    ],
    [
      "A6o",
      "K6o",
      "Q6o",
      "J6o",
      "T6o",
      "96o",
      "86o",
      "76o",
      "66",
      "65s",
      "64s",
      "63s",
      "62s"
    ],
    [
      "A5o",
      "K5o",
      "Q5o",
      "J5o",
      "T5o",
      "95o",
      "85o",
      "75o",
      "65o",
      "55",
      "54s",
      "53s",
      "52s"
    ],
    [
      "A4o",
      "K4o",
      "Q4o",
      "J4o",
      "T4o",
      "94o",
      "84o",
      "74o",
      "64o",
      "54o",
      "44",
      "43s",
      "42s"
    ],
    [
      "A3o",
      "K3o",
      "Q3o",
      "J3o",
      "T3o",
      "93o",
      "83o",
      "73o",
      "63o",
      "53o",
      "43o",
      "33",
      "32s"
    ],
    [
      "A2o",
      "K2o",
      "Q2o",
      "J2o",
      "T2o",
      "92o",
      "82o",
      "72o",
      "62o",
      "52o",
      "42o",
      "32o",
      "22"
    ]
  ],
  "preflopChoices": [
    "Value",
    "Mix Value",
    "Mix Bluff",
    "Call",
    "Fold"
  ],
  "boardCategoryChoices": [
    "Dry",
    "Semi Dry",
    "Wet",
    "Low",
    "Paired"
  ],
  "boardAdvantageChoices": [
    "PFR有利",
    "Caller有利",
    "ほぼ互角"
  ],
  "preflop": [
    {
      "id": "PF001",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "AA",
      "question": "UTG Open → BTN / あなたはBTN / AA",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 1,
      "label": "Value",
      "explanation": "AAはUTG相手でも明確なバリュー。"
    },
    {
      "id": "PF002",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "AQs",
      "question": "UTG Open → BTN / あなたはBTN / AQs",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 2,
      "label": "Mix Value",
      "explanation": "AQsは強いがUTG相手ではCallも3betも混ざる。"
    },
    {
      "id": "PF003",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "A5s",
      "question": "UTG Open → BTN / あなたはBTN / A5s",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 3,
      "label": "Mix Bluff",
      "explanation": "A5sはAブロッカーとホイール可能性がある。"
    },
    {
      "id": "PF004",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "99",
      "question": "UTG Open → BTN / あなたはBTN / 99",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 4,
      "label": "Call",
      "explanation": "99はセットやミドルボードで戦えるためCall。"
    },
    {
      "id": "PF005",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "KJo",
      "question": "UTG Open → BTN / あなたはBTN / KJo",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 5,
      "label": "Fold",
      "explanation": "KJoはUTGレンジに支配されやすい。"
    },
    {
      "id": "PF006",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "AQo",
      "question": "BTN Open → BB / あなたはBB / AQo",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 1,
      "label": "Value",
      "explanation": "BTNの広いオープンに対してAQoはValue。"
    },
    {
      "id": "PF007",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "AJs",
      "question": "BTN Open → BB / あなたはBB / AJs",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 2,
      "label": "Mix Value",
      "explanation": "AJsは3betとCallが混ざる。"
    },
    {
      "id": "PF008",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "KTs",
      "question": "BTN Open → BB / あなたはBB / KTs",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 3,
      "label": "Mix Bluff",
      "explanation": "GTO寄りではMix Bluff。実戦簡略化ならCallでも良い。"
    },
    {
      "id": "PF009",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "55",
      "question": "BTN Open → BB / あなたはBB / 55",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 4,
      "label": "Call",
      "explanation": "BBはポットオッズが良く、55は守りやすい。"
    },
    {
      "id": "PF010",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "K4o",
      "question": "BTN Open → BB / あなたはBB / K4o",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 5,
      "label": "Fold",
      "explanation": "K4oはプレイアビリティが低い。"
    },
    {
      "id": "PF011",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "QQ",
      "question": "UTG Open → BB / あなたはBB / QQ",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 1,
      "label": "Value",
      "explanation": "UTG相手でもQQは強いValue。"
    },
    {
      "id": "PF012",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "JJ",
      "question": "UTG Open → BB / あなたはBB / JJ",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 2,
      "label": "Mix Value",
      "explanation": "JJは強いがUTGの上位レンジに注意。"
    },
    {
      "id": "PF013",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "KTs",
      "question": "UTG Open → BB / あなたはBB / KTs",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 3,
      "label": "Mix Bluff",
      "explanation": "スーテッドで戦えるがバリューではない。"
    },
    {
      "id": "PF014",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "76s",
      "question": "UTG Open → BB / あなたはBB / 76s",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 4,
      "label": "Call",
      "explanation": "BBでポットオッズとプレイアビリティがある。"
    },
    {
      "id": "PF015",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "K9o",
      "question": "UTG Open → BB / あなたはBB / K9o",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 5,
      "label": "Fold",
      "explanation": "UTG相手に支配されやすい。"
    },
    {
      "id": "PF016",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB 3bet → BTN",
      "heroPosition": "BTN",
      "hand": "AA",
      "question": "BTN Open → BB 3bet → BTN / あなたはBTN / AA",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 1,
      "label": "Value",
      "explanation": "3betを受けてもAAは4bet Value。"
    },
    {
      "id": "PF017",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB 3bet → BTN",
      "heroPosition": "BTN",
      "hand": "AQs",
      "question": "BTN Open → BB 3bet → BTN / あなたはBTN / AQs",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 2,
      "label": "Mix Value",
      "explanation": "AQsはCallと4betが混ざる。"
    },
    {
      "id": "PF018",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB 3bet → BTN",
      "heroPosition": "BTN",
      "hand": "A5s",
      "question": "BTN Open → BB 3bet → BTN / あなたはBTN / A5s",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 3,
      "label": "Mix Bluff",
      "explanation": "Aブロッカーで4betブラフ候補。"
    },
    {
      "id": "PF019",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB 3bet → BTN",
      "heroPosition": "BTN",
      "hand": "99",
      "question": "BTN Open → BB 3bet → BTN / あなたはBTN / 99",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 4,
      "label": "Call",
      "explanation": "IPでCallして戦える。"
    },
    {
      "id": "PF020",
      "type": "preflop",
      "mode": "プリフロップ",
      "spot": "BTN Open → BB 3bet → BTN",
      "heroPosition": "BTN",
      "hand": "A9o",
      "question": "BTN Open → BB 3bet → BTN / あなたはBTN / A9o",
      "choices": [
        "Value",
        "Mix Value",
        "Mix Bluff",
        "Call",
        "Fold"
      ],
      "answer": 5,
      "label": "Fold",
      "explanation": "3betポットで支配されやすい。"
    }
  ],
  "boardCategory": [
    {
      "id": "BC001",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "A72r",
      "question": "フロップ：A72r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 1,
      "label": "Dry",
      "explanation": "Aハイ・レインボーでドローが少ない。"
    },
    {
      "id": "BC002",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "K83r",
      "question": "フロップ：K83r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 1,
      "label": "Dry",
      "explanation": "Kハイ・非連結・レインボー。"
    },
    {
      "id": "BC003",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "AJ5r",
      "question": "フロップ：AJ5r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 2,
      "label": "Semi Dry",
      "explanation": "AとJが絡むがレインボーでドローは少なめ。"
    },
    {
      "id": "BC004",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "QT8r",
      "question": "フロップ：QT8r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 2,
      "label": "Semi Dry",
      "explanation": "ストレート関連はあるがssではない。"
    },
    {
      "id": "BC005",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "JT8ss",
      "question": "フロップ：JT8ss",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 3,
      "label": "Wet",
      "explanation": "連結＋ツートーンでドロー多数。"
    },
    {
      "id": "BC006",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "QT9r",
      "question": "フロップ：QT9r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 3,
      "label": "Wet",
      "explanation": "高い連結ボード。互角寄りになりやすい。"
    },
    {
      "id": "BC007",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "654r",
      "question": "フロップ：654r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 4,
      "label": "Low",
      "explanation": "低く連結したボード。"
    },
    {
      "id": "BC008",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "765ss",
      "question": "フロップ：765ss",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 4,
      "label": "Low",
      "explanation": "低中カードで連結、Callerに絡みやすい。"
    },
    {
      "id": "BC009",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "QQ2r",
      "question": "フロップ：QQ2r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 5,
      "label": "Paired",
      "explanation": "Qがペアになったボード。"
    },
    {
      "id": "BC010",
      "type": "board-category",
      "mode": "ボード分類",
      "board": "KK8r",
      "question": "フロップ：KK8r",
      "choices": [
        "Dry",
        "Semi Dry",
        "Wet",
        "Low",
        "Paired"
      ],
      "answer": 5,
      "label": "Paired",
      "explanation": "Kがペアになったボード。"
    }
  ],
  "boardAdvantage": [
    {
      "id": "BA001",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "UTG Open → BTN Call",
      "board": "A72r",
      "question": "UTG Open → BTN Call / A72r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 1,
      "label": "PFR有利",
      "explanation": "UTGがAA/AK/AQを多く持つ。"
    },
    {
      "id": "BA002",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "UTG Open → BTN Call",
      "board": "654r",
      "question": "UTG Open → BTN Call / 654r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 2,
      "label": "Caller有利",
      "explanation": "BTNは低いポケットやコネクターを多く持つ。"
    },
    {
      "id": "BA003",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "UTG Open → BTN Call",
      "board": "QT9r",
      "question": "UTG Open → BTN Call / QT9r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 3,
      "label": "ほぼ互角",
      "explanation": "高いウェットボードで双方が強くヒットする。"
    },
    {
      "id": "BA004",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "BTN Open → BB Call",
      "board": "AJ5r",
      "question": "BTN Open → BB Call / AJ5r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 1,
      "label": "PFR有利",
      "explanation": "BTNは強いAxを多く持つ。"
    },
    {
      "id": "BA005",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "BTN Open → BB Call",
      "board": "654r",
      "question": "BTN Open → BB Call / 654r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 2,
      "label": "Caller有利",
      "explanation": "BBは低いカードを広く守る。"
    },
    {
      "id": "BA006",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "BTN Open → BB Call",
      "board": "QT9r",
      "question": "BTN Open → BB Call / QT9r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 3,
      "label": "ほぼ互角",
      "explanation": "BTNもBBも強く絡むため単純なCaller有利ではない。"
    },
    {
      "id": "BA007",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "UTG Open → BB Call",
      "board": "A83r",
      "question": "UTG Open → BB Call / A83r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 1,
      "label": "PFR有利",
      "explanation": "UTGのAxが強い。"
    },
    {
      "id": "BA008",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "UTG Open → BB Call",
      "board": "765ss",
      "question": "UTG Open → BB Call / 765ss",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 2,
      "label": "Caller有利",
      "explanation": "BBの広い守備レンジが強く絡む。"
    },
    {
      "id": "BA009",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "BTN Open → BB Call",
      "board": "QQ2r",
      "question": "BTN Open → BB Call / QQ2r",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 1,
      "label": "PFR有利",
      "explanation": "ペアボードはPFRのレンジ優位が出やすい。"
    },
    {
      "id": "BA010",
      "type": "board-advantage",
      "mode": "有利不利",
      "spot": "BTN Open → BB Call",
      "board": "JT8ss",
      "question": "BTN Open → BB Call / JT8ss",
      "choices": [
        "PFR有利",
        "Caller有利",
        "ほぼ互角"
      ],
      "answer": 3,
      "label": "ほぼ互角",
      "explanation": "BBも多く絡むがBTNも強いブロードウェイを持つ。"
    }
  ],
  "integrated": [
    {
      "id": "IQ001",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "A5s",
      "preflopAnswer": 3,
      "preflopLabel": "Mix Bluff",
      "flop": "A72r",
      "boardAnswer": 1,
      "boardLabel": "PFR有利",
      "explainPreflop": "A5sはAブロッカー＋ホイール可能性がありMix Bluff。",
      "explainBoard": "A72rはUTGがAA/AK/AQを多く持つ。",
      "explainHand": "A5sはAヒットだがキッカーに注意。"
    },
    {
      "id": "IQ002",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "UTG Open → BTN",
      "heroPosition": "BTN",
      "hand": "99",
      "preflopAnswer": 4,
      "preflopLabel": "Call",
      "flop": "962r",
      "boardAnswer": 2,
      "boardLabel": "Caller有利",
      "explainPreflop": "99はCall中心。",
      "explainBoard": "962rはBTN側が99/66/22を持ちやすい。",
      "explainHand": "99はトップセット。"
    },
    {
      "id": "IQ003",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "KTs",
      "preflopAnswer": 3,
      "preflopLabel": "Mix Bluff",
      "flop": "JT8ss",
      "boardAnswer": 3,
      "boardLabel": "ほぼ互角",
      "explainPreflop": "GTO寄りではMix Bluff。実戦簡略化ならCallも自然。",
      "explainBoard": "JT8ssはBBもBTNも強く絡み、互角寄りに修正。",
      "explainHand": "KTsはドローに絡みやすい。"
    },
    {
      "id": "IQ004",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "QJs",
      "preflopAnswer": 2,
      "preflopLabel": "Mix Value",
      "flop": "QT9r",
      "boardAnswer": 3,
      "boardLabel": "ほぼ互角",
      "explainPreflop": "QJsは強いスーテッド系。",
      "explainBoard": "QT9rは双方が強くヒットするため互角寄り。",
      "explainHand": "QJsはトップペア＋ガットで強い。"
    },
    {
      "id": "IQ005",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "BTN Open → BB",
      "heroPosition": "BB",
      "hand": "AJs",
      "preflopAnswer": 2,
      "preflopLabel": "Mix Value",
      "flop": "AJ5r",
      "boardAnswer": 1,
      "boardLabel": "PFR有利",
      "explainPreflop": "AJsはMix Value。",
      "explainBoard": "AJ5rはBTNが強いAxを多く持つ。",
      "explainHand": "自分は強いがレンジ全体はPFR有利。"
    },
    {
      "id": "IQ006",
      "type": "integrated",
      "mode": "2ステップ実戦",
      "spot": "UTG Open → BB",
      "heroPosition": "BB",
      "hand": "76s",
      "preflopAnswer": 4,
      "preflopLabel": "Call",
      "flop": "765ss",
      "boardAnswer": 2,
      "boardLabel": "Caller有利",
      "explainPreflop": "76sはBBでCall候補。",
      "explainBoard": "765ssはBBの広いレンジが強く絡む。",
      "explainHand": "76sは非常に強くヒット。"
    }
  ],
  "references": {
    "strategy": {
      "UTG vs BTN": {
        "3bet Value": [
          "AA",
          "AKs",
          "AKo",
          "KK",
          "QQ"
        ],
        "Mix Value": [
          "AQs",
          "KQs",
          "AQo",
          "JJ",
          "TT"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs"
        ],
        "Call": [
          "AJs",
          "ATs",
          "KJs",
          "QJs",
          "QTs",
          "AJo",
          "JTs",
          "J9s",
          "T9s",
          "T8s",
          "99",
          "98s",
          "88",
          "87s",
          "77",
          "76s",
          "66",
          "65s",
          "55",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "KQo",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "KJo",
          "QJo",
          "J8s",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      },
      "BTN vs BB": {
        "3bet Value": [
          "AA",
          "AKs",
          "AQs",
          "AKo",
          "KK",
          "AQo",
          "QQ",
          "JJ",
          "TT"
        ],
        "Mix Value": [
          "AJs",
          "ATs",
          "KQs",
          "KJs",
          "KQo",
          "QJs",
          "JTs",
          "99",
          "88"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs",
          "K9s",
          "QTs",
          "J9s",
          "T9s",
          "76s",
          "65s",
          "54s"
        ],
        "Call": [
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "AJo",
          "KJo",
          "QJo",
          "J8s",
          "J7s",
          "J6s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T8s",
          "T7s",
          "A9o",
          "T9o",
          "98s",
          "97s",
          "A8o",
          "98o",
          "87s",
          "86s",
          "A7o",
          "77",
          "75s",
          "A6o",
          "66",
          "64s",
          "A5o",
          "55",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "Q4s",
          "Q3s",
          "Q2s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "K9o",
          "Q9o",
          "J9o",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "85s",
          "84s",
          "83s",
          "82s",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "74s",
          "73s",
          "72s",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "63s",
          "62s",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      },
      "UTG vs BB": {
        "3bet Value": [
          "AA",
          "AKs",
          "AKo",
          "KK",
          "QQ"
        ],
        "Mix Value": [
          "AQs",
          "KQs",
          "AQo",
          "JJ",
          "TT"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs",
          "QTs"
        ],
        "Call": [
          "AJs",
          "ATs",
          "KJs",
          "KQo",
          "QJs",
          "AJo",
          "JTs",
          "J9s",
          "T9s",
          "T8s",
          "99",
          "98s",
          "88",
          "87s",
          "77",
          "76s",
          "66",
          "65s",
          "55",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "KJo",
          "QJo",
          "J8s",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      },
      "UTG vs BTN 3bet": {
        "4bet Value": [
          "AA",
          "AKs",
          "AKo",
          "KK"
        ],
        "Mix Value": [
          "AQs",
          "QQ",
          "JJ"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s"
        ],
        "Call": [
          "AJs",
          "KQs",
          "AQo",
          "TT",
          "99"
        ],
        "Fold": [
          "ATs",
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "KJs",
          "KTs",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "KQo",
          "QJs",
          "QTs",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "AJo",
          "KJo",
          "QJo",
          "JTs",
          "J9s",
          "J8s",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T9s",
          "T8s",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "98s",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "88",
          "87s",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "77",
          "76s",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "66",
          "65s",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "55",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "44",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "33",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o",
          "22"
        ]
      },
      "BTN vs BB 3bet": {
        "4bet Value": [
          "AA",
          "AKs",
          "AKo",
          "KK",
          "QQ"
        ],
        "Mix Value": [
          "AQs",
          "KQs",
          "AQo",
          "JJ",
          "TT"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs",
          "QTs",
          "J9s",
          "T9s"
        ],
        "Call": [
          "AJs",
          "ATs",
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "KJs",
          "KQo",
          "QJs",
          "KJo",
          "JTs",
          "J8s",
          "T8s",
          "99",
          "98s",
          "97s",
          "88",
          "87s",
          "77",
          "76s",
          "66",
          "65s",
          "55",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "AJo",
          "QJo",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      }
    },
    "sb": {
      "SB First In": {
        "Open Value": [
          "AA",
          "AKs",
          "AQs",
          "AJs",
          "AKo",
          "KK",
          "KQs",
          "AQo",
          "QQ",
          "JJ",
          "TT",
          "99",
          "88"
        ],
        "Mix Value": [
          "ATs",
          "A9s",
          "A8s",
          "KJs",
          "KTs",
          "KQo",
          "QJs",
          "QTs",
          "AJo",
          "JTs",
          "77",
          "66",
          "55"
        ],
        "Mix Bluff": [
          "A7s",
          "A6s",
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "KJo",
          "QJo",
          "J9s",
          "J8s",
          "J7s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T9s",
          "T8s",
          "T7s",
          "A9o",
          "98s",
          "A8o",
          "87s",
          "76s"
        ],
        "Call": [],
        "Fold": [
          "Q4s",
          "Q3s",
          "Q2s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "65s",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "44",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "33",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o",
          "22"
        ]
      },
      "BTN Open → SB": {
        "3bet Value": [
          "AA",
          "AKs",
          "AQs",
          "AKo",
          "KK",
          "AQo",
          "QQ",
          "JJ",
          "TT"
        ],
        "Mix Value": [
          "AJs",
          "ATs",
          "KQs",
          "KJs",
          "KQo",
          "QJs",
          "AJo",
          "JTs",
          "99",
          "88",
          "77"
        ],
        "Mix Bluff": [
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs",
          "K9s",
          "QTs",
          "Q9s",
          "J9s",
          "T9s",
          "98s",
          "87s",
          "76s",
          "65s"
        ],
        "Call": [
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "K8s",
          "K7s",
          "Q8s",
          "J8s",
          "T8s",
          "66",
          "55",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "KJo",
          "QJo",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      }
    },
    "open": {
      "UTG Open": {
        "Open": [
          "AA",
          "AKs",
          "AQs",
          "AJs",
          "ATs",
          "AKo",
          "KK",
          "KQs",
          "KJs",
          "AQo",
          "KQo",
          "QQ",
          "QJs",
          "AJo",
          "JJ",
          "JTs",
          "TT",
          "T9s",
          "99",
          "88",
          "77"
        ],
        "Fold": [
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "KTs",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "QTs",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "KJo",
          "QJo",
          "J9s",
          "J8s",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "T8s",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "98s",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "87s",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "76s",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "66",
          "65s",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "55",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "44",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "33",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o",
          "22"
        ]
      },
      "BTN Open": {
        "Open": [
          "AA",
          "AKs",
          "AQs",
          "AJs",
          "ATs",
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "AKo",
          "KK",
          "KQs",
          "KJs",
          "KTs",
          "K9s",
          "K8s",
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "AQo",
          "KQo",
          "QQ",
          "QJs",
          "QTs",
          "Q9s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "AJo",
          "KJo",
          "QJo",
          "JJ",
          "JTs",
          "J9s",
          "J8s",
          "J7s",
          "ATo",
          "KTo",
          "QTo",
          "JTo",
          "TT",
          "T9s",
          "T8s",
          "T7s",
          "A9o",
          "T9o",
          "99",
          "98s",
          "97s",
          "A8o",
          "98o",
          "88",
          "87s",
          "86s",
          "77",
          "76s",
          "75s",
          "66",
          "65s",
          "64s",
          "55",
          "54s",
          "44",
          "33",
          "22"
        ],
        "Fold": [
          "Q4s",
          "Q3s",
          "Q2s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "K9o",
          "Q9o",
          "J9o",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o"
        ]
      },
      "SB First In": {
        "Open": [
          "AA",
          "AKs",
          "AQs",
          "AJs",
          "ATs",
          "A9s",
          "A8s",
          "A7s",
          "A6s",
          "A5s",
          "A4s",
          "A3s",
          "A2s",
          "AKo",
          "KK",
          "KQs",
          "KJs",
          "KTs",
          "K9s",
          "K8s",
          "AQo",
          "KQo",
          "QQ",
          "QJs",
          "QTs",
          "Q9s",
          "AJo",
          "KJo",
          "QJo",
          "JJ",
          "JTs",
          "J9s",
          "ATo",
          "JTo",
          "TT",
          "T9s",
          "T8s",
          "99",
          "98s",
          "88",
          "87s",
          "77",
          "76s",
          "66",
          "55"
        ],
        "Fold": [
          "K7s",
          "K6s",
          "K5s",
          "K4s",
          "K3s",
          "K2s",
          "Q8s",
          "Q7s",
          "Q6s",
          "Q5s",
          "Q4s",
          "Q3s",
          "Q2s",
          "J8s",
          "J7s",
          "J6s",
          "J5s",
          "J4s",
          "J3s",
          "J2s",
          "KTo",
          "QTo",
          "T7s",
          "T6s",
          "T5s",
          "T4s",
          "T3s",
          "T2s",
          "A9o",
          "K9o",
          "Q9o",
          "J9o",
          "T9o",
          "97s",
          "96s",
          "95s",
          "94s",
          "93s",
          "92s",
          "A8o",
          "K8o",
          "Q8o",
          "J8o",
          "T8o",
          "98o",
          "86s",
          "85s",
          "84s",
          "83s",
          "82s",
          "A7o",
          "K7o",
          "Q7o",
          "J7o",
          "T7o",
          "97o",
          "87o",
          "75s",
          "74s",
          "73s",
          "72s",
          "A6o",
          "K6o",
          "Q6o",
          "J6o",
          "T6o",
          "96o",
          "86o",
          "76o",
          "65s",
          "64s",
          "63s",
          "62s",
          "A5o",
          "K5o",
          "Q5o",
          "J5o",
          "T5o",
          "95o",
          "85o",
          "75o",
          "65o",
          "54s",
          "53s",
          "52s",
          "A4o",
          "K4o",
          "Q4o",
          "J4o",
          "T4o",
          "94o",
          "84o",
          "74o",
          "64o",
          "54o",
          "44",
          "43s",
          "42s",
          "A3o",
          "K3o",
          "Q3o",
          "J3o",
          "T3o",
          "93o",
          "83o",
          "73o",
          "63o",
          "53o",
          "43o",
          "33",
          "32s",
          "A2o",
          "K2o",
          "Q2o",
          "J2o",
          "T2o",
          "92o",
          "82o",
          "72o",
          "62o",
          "52o",
          "42o",
          "32o",
          "22"
        ]
      }
    },
    "terms": [
      {
        "term": "PFR",
        "body": "Pre Flop Raiser。プリフロップで最後にレイズした人。フロップではPFR側とCaller側のどちらが有利かを見る。"
      },
      {
        "term": "Caller",
        "body": "プリフロップでコールして参加した側。BTNやBBのコールレンジは低いカードやコネクターを含みやすい。"
      },
      {
        "term": "Dry",
        "body": "ドローが少ないボード。例：A72r、K83r。PFR有利になりやすい。"
      },
      {
        "term": "Wet",
        "body": "ストレートやフラッシュドローが多いボード。例：JT8ss、987ss。"
      },
      {
        "term": "r / ss / m",
        "body": "rはRainbow、ssはTwo-tone、mはMonotone。A72rは3スート別、JT8ssは同スート2枚。"
      },
      {
        "term": "プレイアビリティ",
        "body": "フロップ以降でどれだけ戦いやすいか。スーテッド、連結、ポケットは高い。"
      },
      {
        "term": "ブロッカー",
        "body": "自分のカードが相手の強い役の組み合わせを減らすこと。A5sはAA/AK/AQを減らす。"
      },
      {
        "term": "スーテッドブロードウェイ",
        "body": "T以上のカード同士で同じスート。AKs, KQs, QJs, JTsなど。"
      }
    ]
  }
};

const STORAGE_KEY = "pokerRangeTrainerV4";
let state = { mode:"integrated", order:[], index:0, step:"preflop", score:0, total:0, answered:false };
const quizModes = ["integrated","preflop","boardCategory","boardAdvantage","mistakes"];
const refModes = ["refStrategy","refSB","refOpen","terms"];

function loadStore(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{stats:{},mistakes:[]}}catch{return{stats:{},mistakes:[]}}}
function saveStore(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function getQuestions(mode){
  if(mode==="integrated")return DATA.integrated;
  if(mode==="preflop")return DATA.preflop;
  if(mode==="boardCategory")return DATA.boardCategory;
  if(mode==="boardAdvantage")return DATA.boardAdvantage;
  if(mode==="mistakes"){
    const ids=new Set(loadStore().mistakes||[]);
    return [...DATA.integrated,...DATA.preflop,...DATA.boardCategory,...DATA.boardAdvantage].filter(q=>ids.has(q.id));
  }
  return DATA.integrated;
}
function modeTitle(mode){return {integrated:"2ステップ実戦",preflop:"プリフロップ",boardCategory:"ボード分類",boardAdvantage:"有利不利",mistakes:"間違い復習",refStrategy:"戦略表",refSB:"SB戦略",refOpen:"オープンレンジ",terms:"用語集"}[mode]||mode}
function startMode(mode){
  state.mode=mode;
  document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));
  if(refModes.includes(mode)){ renderReference(mode); return; }
  const qs=getQuestions(mode);
  if(mode==="mistakes"&&qs.length===0){alert("復習する間違い問題はまだありません。"); return;}
  state.order=[...Array(qs.length).keys()]; state.index=0; state.step=mode==="integrated"?"preflop":"single"; state.score=0; state.total=0; state.answered=false; renderQuiz();
}
function currentList(){return getQuestions(state.mode)}
function currentQuestion(){return currentList()[state.order[state.index]]}
function choicesFor(q){ if(q.type==="preflop")return DATA.preflopChoices; if(q.type==="board-category")return DATA.boardCategoryChoices; if(q.type==="board-advantage")return DATA.boardAdvantageChoices; if(q.type==="integrated")return state.step==="preflop"?DATA.preflopChoices:DATA.boardAdvantageChoices; return []}
function answerFor(q){return q.type==="integrated"?(state.step==="preflop"?q.preflopAnswer:q.boardAnswer):q.answer}
function labelFor(q){return q.type==="integrated"?(state.step==="preflop"?q.preflopLabel:q.boardLabel):q.label}
function renderQuiz(){
  document.querySelector("#quizArea").style.display="block"; document.querySelector("#refArea").style.display="none";
  const q=currentQuestion(), list=currentList();
  document.querySelector("#modeTitle").textContent=modeTitle(state.mode);
  document.querySelector("#progress").textContent=`${state.index+1} / ${list.length}`;
  document.querySelector("#score").textContent=`${state.score} / ${state.total}`;
  document.querySelector("#phase").textContent=q.type==="integrated"?(state.step==="preflop"?"STEP1：プリフロップアクション":"STEP2：フロップ有利不利"):q.mode;
  document.querySelector("#spot").textContent=q.spot||"-";
  document.querySelector("#hero").textContent=q.heroPosition||"-";
  document.querySelector("#hand").textContent=q.hand||"-";
  document.querySelector("#board").textContent=q.type==="integrated"?(state.step==="board"?q.flop:"STEP1正解後"):(q.board||"-");
  document.querySelector("#feedback").innerHTML=""; document.querySelector("#explanation").innerHTML=""; document.querySelector("#nextBtn").disabled=true;
  const box=document.querySelector("#choices"); box.innerHTML="";
  choicesFor(q).forEach((ch,i)=>{ const btn=document.createElement("button"); btn.className="choice"; btn.innerHTML=`<span>${i+1}</span>${ch}`; btn.onclick=()=>answer(i+1,btn); box.appendChild(btn); });
}
function addMistake(id){const s=loadStore(); const set=new Set(s.mistakes||[]); set.add(id); s.mistakes=[...set]; saveStore(s)}
function removeMistake(id){const s=loadStore(); s.mistakes=(s.mistakes||[]).filter(x=>x!==id); saveStore(s)}
function recordStat(ok){const s=loadStore(); const k=state.mode; s.stats[k]=s.stats[k]||{ok:0,total:0}; s.stats[k].total++; if(ok)s.stats[k].ok++; saveStore(s)}
function answer(num,clicked){
  if(state.answered)return; const q=currentQuestion(); const correct=answerFor(q), ok=num===correct; state.answered=true; state.total++; if(ok)state.score++; recordStat(ok); ok?removeMistake(q.id):addMistake(q.id);
  document.querySelectorAll(".choice").forEach((b,i)=>{b.disabled=true; if(i+1===correct)b.classList.add("correct"); if(b===clicked&&!ok)b.classList.add("wrong")});
  document.querySelector("#feedback").innerHTML=ok?"⭕ 正解！":`❌ 不正解。正解は ${correct}. ${labelFor(q)}`;
  document.querySelector("#explanation").innerHTML=buildExplanation(q);
  document.querySelector("#nextBtn").disabled=false; document.querySelector("#nextBtn").textContent=(q.type==="integrated"&&state.step==="preflop")?"フロップ問題へ":(state.index+1===currentList().length?"最初に戻る":"次の問題へ");
  document.querySelector("#score").textContent=`${state.score} / ${state.total}`;
}
function buildExplanation(q){
  if(q.type==="integrated"){
    if(state.step==="preflop")return `<h3>プリフロップ解説</h3><p>${q.explainPreflop}</p><p class="hint">GTO寄りと実戦簡略化で答えがズレるハンドもあります。違和感がある時は参照モードで確認してください。</p>`;
    return `<h3>プリフロップ解説</h3><p>${q.explainPreflop}</p><h3>ボード解説</h3><p>${q.explainBoard}</p><h3>ハンド解説</h3><p>${q.explainHand}</p>`;
  }
  return `<h3>解説</h3><p>${q.explanation}</p>`;
}
function next(){
  const q=currentQuestion();
  if(q.type==="integrated"&&state.step==="preflop"){state.step="board"; state.answered=false; renderQuiz(); return;}
  state.index++; if(state.index>=currentList().length)state.index=0;
  state.step=state.mode==="integrated"?"preflop":"single"; state.answered=false; renderQuiz();
}
function shuffle(){ const qs=currentList(); state.order=[...Array(qs.length).keys()]; for(let i=state.order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [state.order[i],state.order[j]]=[state.order[j],state.order[i]]} state.index=0; state.step=state.mode==="integrated"?"preflop":"single"; state.score=0; state.total=0; renderQuiz();}
function resetStats(){ if(confirm("成績と間違い復習リストをリセットしますか？")){localStorage.removeItem(STORAGE_KEY); state.score=0; state.total=0; renderQuiz();}}

function renderReference(mode){
  document.querySelector("#quizArea").style.display="none"; document.querySelector("#refArea").style.display="block";
  document.querySelector("#modeTitle").textContent=modeTitle(mode); document.querySelector("#progress").textContent="-"; document.querySelector("#score").textContent="-";
  const area=document.querySelector("#refArea");
  if(mode==="terms"){ area.innerHTML=`<section class="card"><h2>用語集</h2>${DATA.references.terms.map(t=>`<div class="term"><h3>${t.term}</h3><p>${t.body}</p></div>`).join("")}</section>`; return; }
  const source = mode==="refStrategy"?DATA.references.strategy:(mode==="refSB"?DATA.references.sb:DATA.references.open);
  const spotNames=Object.keys(source);
  area.innerHTML=`<section class="card ref-controls"><h2>${modeTitle(mode)}</h2><label>スポット<select id="refSpot"></select></label><label>アクション<select id="refAction"></select></label><div id="rangeGrid"></div></section>`;
  const spotSel=document.querySelector("#refSpot"), actionSel=document.querySelector("#refAction");
  spotNames.forEach(s=>spotSel.add(new Option(s,s)));
  function updateActions(){ actionSel.innerHTML=""; Object.keys(source[spotSel.value]).forEach(a=>actionSel.add(new Option(a,a))); updateGrid(); }
  function updateGrid(){ const keep=new Set(source[spotSel.value][actionSel.value]); document.querySelector("#rangeGrid").innerHTML = makeRangeGrid(keep); }
  spotSel.onchange=updateActions; actionSel.onchange=updateGrid; updateActions();
}
function makeRangeGrid(keep){
  return `<div class="range-grid">${DATA.matrix.flat().map(h=>`<div class="cell ${keep.has(h)?"keep":"gray"}">${h}</div>`).join("")}</div><p class="note">色付き＝対象レンジ / グレー＝対象外</p>`;
}
document.addEventListener("DOMContentLoaded",()=>{
  document.querySelectorAll(".mode-btn").forEach(btn=>btn.onclick=()=>startMode(btn.dataset.mode));
  document.querySelector("#nextBtn").onclick=next; document.querySelector("#shuffleBtn").onclick=shuffle; document.querySelector("#resetBtn").onclick=resetStats;
  startMode("integrated");
});
